### ISSUE TITLE
Error: Studio locks up when it can't find a file

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#90] opened 2016-07-18 03:51 UTC
I've just been refactoring my Wakanda project.

After the refactoring I went to open the project in Studio (v1.1.0) and it presented a dialog telling me that a certain file did not exist.

Strange because the file it was looking for was not even in the project folder (it was actually in a 4D project folder???).

Regardless, I click on OK in the dialog and nothing happens. I end up having to forces quit studio.

This is so frustrating.

I know it is not in your DNA to use the standard system toolboxes to do anything and you feel like you have to write your own dialogs – but this is what happens when you do. This has been a problem since the earliest days of 4D – Apple or Microsoft update their UI and the 4D dialogs display the old UI.

In this case you've decided that you will force 'flat' dialogs on us regardless of the UI of the OS.

As I said, this is so frustrating. I will now have to spend another couple of hours finding the source of this problem before I can get back to where I was.

(Another thought – couldn't you just write any errors to the console rather than displaying a dialog. That way we could see the error but still be able to work on other parts of the project.)

**Comment by Ganbin** [comment] 2016-07-18 12:46
Hi,
This is an anoying issue I fall some weeks before.

To fix it you can delete the `<Solution_Path>/<SolutioName>.<username>.waPreferences`.

So next time you will open the solution in the studio, it will not try to open this file again.

This `.waPreferences` file keep the preferences of the current state of the solution, like which files are open for example. To delete it will not affect anything because the studio will create a new one if it is missing.

**Comment by alcada** [comment] 2016-07-18 15:41
Hello
This preferences file should also register the panels that the user closed in the last session. Since I moved to Wakanda 11 the first thing I have to do all the time when I open any solution is to close the bottom panel with open console (which occupies nearly half of the available area of the screen).

**Comment by Ganbin** [comment] 2016-07-18 15:53
@alcada Yes it could be nice. Even to store the size of the panel to not have to resize everytime.

**Comment by chriscurnow** [comment] 2016-07-18 23:34
Yes, deleting the preferences file fixes it.

But it is a silly bug. Sure Wakanda can tell me it can't find a file – but for it to lock up just because it can't find a file is inexcusable. There is a fundamental problem in the code that displays this dialog. As I said above, I just wish Wakanda would use the standard OS toolbox to display dialogs rather than having its own code and own UI.

**Comment by AaronLavers** [comment] 2016-07-20 00:56
@chriscurnow we excused Windows for years for locking up when it couldn't find System32 ;)

**Comment by chriscurnow** [comment] 2016-07-20 01:17
Windows? Whats that? - Oh, I remember. Yes I have heard of it but never used it:)

**Comment by FrancoisMarchal** [comment] 2016-08-05 08:15
@alcada all the tabs positions are recorded, and it is up to each panel to tell if it's position has to be remembered. Concerning the Console panel, we had a discussion internally, I was not a big fan of opening it each time the solution was opened, but our product owner argued that it was good to have it always opened so user can immediately see if everything runs well during solution opening.

The good point is that you can change easily this behavior by yourself while as most of Wakanda interface, it's done by extension in JS. 

Select the file { Wakanda Studio Application folder (or bundle on Mac) }/extensions/wakanda-extension-mobile-console/manifest.json

Open it, and change the following lines:

		"actions": [{
			"name": "open",
			"title": "Open Console",
			"trigger": [{
				"event": "onSolutionOpened"
			}]
		}, {
to

		"actions": [{
			"name": "open",
			"title": "Open Console"
		}, {

This will remove the trigger that open the console everytime a solution is opened

**Comment by FrancoisMarchal** [comment] 2016-08-05 08:24
@chriscurnow Everytime you close a solution, the Studio will remember the files who were opened in tabs, so when you reopen the solution you find all your files back. We keep relative paths to the files that are located in the solution, so you can work with any external disk, close your solution on a desktop computer, move your disk to a laptop and reopen your solution and gets all your files back even if they have now a different fullpath. But if you open files outside the solution, we store the full path that may vary (or you may have deleted or moved the files). In this case we show up this dialog, but it should not hang the studio, we have to investigate about that. I guess you are using a Macintosh? We had some nasty bugs that looks like that when we were trying to display two modal dialogs as sheetwindow, MacOS does not like that at all and hangs, so it may be something like that, but the issue has been fixed a while ago.

**Comment by alcada** [comment] 2016-08-05 10:27
Hello @FrancoisMarchal and thanks for the tips. Editing the manifest.json works OK.
Thinking better, now I can see the point of wakanda product owner, concerning the user alert to the messages (errors and warnings) generated during studio startup.
That said, the missing functionality that I think that may be consensual, would be registering the position and dimensions of the three panels (left, right and bottom) that user sets before quits the studio. I see the advantage of always re-open the bottom panel (with messages from the console), even if the user has closed it previously, but opened with the same dimensions previously specified by the user. Note that Wakanda studio has already this remenbering behaviour but only regarding the leftmost panel (with "home" tab and opened solution tabs), at left of the "called" left  panel.

**Comment by chriscurnow** [comment] 2016-08-08 04:33
@FrancoisMarchal yes I am using a Mac. Of course I can understand Studio complaining that it can't find a file. I would have no problem with that. The problem is that it hangs and I have a dialog sitting there that I can't dismiss.

**Comment by yboukhata** [comment] 2016-08-08 09:22
@chriscurnow 
About closing the **Studio Console** when opening a console, we can add a feature to set this behaviour as a preference in **Studio Preferences** if needed.

**Comment by chriscurnow** [comment] 2016-09-17 12:09
@FrancoisMarchal the fundamental problem here seems to be related to the fact you do not use the standard OS dialog. Rather you force a non standard UI on us that is going to give us these types of errors. I personally find the non standard UI extremely annoying. In every other application an OK button is an OK button. It is the same shape and colour. But in Wakanda it is not. I really don't know why you do that.

**Comment by hamzahik** [comment] 2016-09-18 14:27
@chriscurnow some parts of the UI are standard OS UI and some are not. When you create a desktop app with multiple OS targets you can't afford to have separate UI code for every UI item and every OS.

**Comment by hamzahik** [comment] 2016-09-22 08:03
1.1.0 released with the fix. @chriscurnow please let us know if you still reproduce the problem.

**Closed by hamzahik** 2016-09-22 08:03 UTC
Labels: bug, Studio
