### ISSUE TITLE
Issues where debugger will not rpeocess authentication thread in some projects.  

### ISSUE THREAD

**Issue by erlicthemad** [Wakanda/wakanda-issues#262] opened 2018-06-18 16:34 UTC
This is a continuation of 257 since 257 seems to be ignored. 

Well after a long night pondering what can be done. I tried to build a new project. That project behaved as expected. I have no idea what happened in this 14 solution project that made it die. But getting help with fixing or figuring out what needs to be done to fix the issue is fruitless. It was easier to throw out all the work that was done and rebuild. So I now am rebuilding my solution and all 14 projects in the solution for a brand new Wakanda job. Some of the source code I can try to recover from my git repository, but still, manual reconstruction is a real pain. Fortunately, I don't have a team working on the project, or it would be far worse.

### **This would be my suggestion to prevent this kind of disaster from happening to others.**
Either add a sanitizer or build checker that will walk the files and look for errors that could cause the bootstrap function to due to a horrible death. Specifically, my issues seem to relate to trying to use the following call in bootstrap.

directory.setLoginManager("login/login", "Admin");

I can upload the solution files here zipped if you want to see the issues with the debugger not working and the issues causing the delay in the editor behavior. The project is a 3GB zip ed project. Mostly due to the attached git repository. It looks like GIT is sucking up the database files in the dev environments.

**Comment by JegoYann** [comment] 2018-06-19 07:16
Duplicate of #257. Check #257 for history.

**Closed by JegoYann** 2018-06-19 07:16 UTC
