### ISSUE TITLE
directory.currentSession returns a default guest session in RPC

### ISSUE THREAD

**Issue by NAMSGithub** [Wakanda/wakanda-issues#215] opened 2017-10-02 14:34 UTC
Wakanda 2.1.0 Mac OS 10.12.6

Upon successful login, returning data in the `storage` property of the login listener's return object does not cause that data to stay with the session. Example below. I noticed this in my solution and confirmed with Ricardo Mello's "Login Example" example solution.

![image-1](https://user-images.githubusercontent.com/24443636/31082571-01768ae0-a755-11e7-866d-d424b019d96d.png)

**Comment by NAMSGithub** [comment] 2017-10-03 17:29
Since session storage is how I am able to validate a user's access rights, I went ahead and posted a case to TAOW: #137212.

**Comment by liuxiang625** [comment] 2017-10-03 20:35
Are you aiming to return data stored in sessionStorage to client side? This will not work because session storage is only available server side.

If not, can you describe what are the steps to recreate the problem? Did this issue also occur in versions before 2.1.0? 

Note: It seems like this case has nothing to with 4D. It is better handled here on Github instead of 4D TAOW. I will close that TAOW case.

Thanks!

**Comment by NAMSGithub** [comment] 2017-10-03 20:54
I am trying to retrieve the session information on the server side.

Simply create a login listener and in the return, give the storage property an object with data. That data does not save to the session like it should. I have an example solution I can send.

This was not an issue on 1.x or previous.

**Comment by liuxiang625** [comment] 2017-10-03 22:54
Hi Aaron,

Can you test put a pair of single quotes around **time** like **'time'** ?  That seemed to work for me.

`return {
	  	ID: 545642165412,
        	name: username,
        	fullName: username,
        	belongsTo: 'free-customer',
        	lifeTime: 60*60,
        	storage: {'time':new Date()}	
	  }`

![screen shot 2017-10-03 at 3 54 13 pm](https://user-images.githubusercontent.com/1305420/31152944-2f27eaac-a853-11e7-89a4-f611142f2f44.png)

**Comment by NAMSGithub** [comment] 2017-10-04 15:14
That did not work for me. What is your Wakanda version / can you give me a copy of your solution?

**Comment by liuxiang625** [comment] 2017-10-04 16:31
This is the code of the login module. For simplicity of testing, I just return the same user object to every login request and use REST to login (http://127.0.0.1:8081/rest/$directory/login(jsmith,johnny1))

`exports.login = function(username, password){
	  return {
	  		ID: 545642165412,
        	name: username,
        	fullName: username,
        	belongsTo: 'free-customer',
        	lifeTime: 60*60,
        	storage: {'time':new Date()}  	
	  }
}`

I tested in 2.1.0 and 2.2.0 on Mac and both work for me.

**Comment by NAMSGithub** [comment] 2017-10-05 15:45
Okay. I was wrong about the problem. The data does save to the session storage correctly. The issue that I have is that when I call an RPC from the client side, the RPC runs `directory.currentSession` and it returns an empty default guest session instead of the user session.

**Comment by liuxiang625** [comment] 2017-10-05 16:49
It seems your problem is not related to login listener and session storage, it's `directory.currentSession` in RPC call returns guest session all the time.

Does `directory.currentSession` return correct user session in version 1.x?

**Comment by NAMSGithub** [comment] 2017-10-05 17:17
Correct- I updated the title to reflect that.

`currentSession()` in 1.x would return the user's session when I would call RPC, but I am calling the RPC in 2.x differently now because the prototyper is gone (I used to use the prototyper to declare the RPC module). I wonder if this is why I am not able to get the user session with `directory.currentSession`.

I tried calling RPC differently today using your guide here but it says that WAF is not found, so maybe this guide does not work for 2.x. https://stackoverflow.com/questions/44277928/wakanda-rpc-client-side

**Comment by NAMSGithub** [comment] 2017-10-05 18:05
I got RPC working using your guide now, but I have the same problem- `directory.currentSession` returns a default guest session that way too.

**Comment by liuxiang625** [comment] 2017-10-05 18:14
The [documentation](http://doc.wakanda.org/home2.en.html#/Using-JSON-RPC-Services/Upgrading-JSON-RPC-from-Wakanda-v1-to-v2-and-higher.200-951454.en.html) states that "Starting with Wakanda v2, the RPC implementation is based on CommonJS architecture, which is not compatible with the previous architecture. In particular, declaring RPC function files as "roles" and namespacing functions through the Prototyper **do not work anymore**. " 

In my understanding, Wakanda 2.x does not have a JSON-RPC client like 1.x that requires instaciation and stores client session. It seems to me all RPC calls under the new architecture are session-less. I will test and confirm with the team to see if this is the expected behavior.

If storeing and retriving client session info are required in you app. Will you consider using HttpRequestHandler or Dataclass method as an workaround?

**Comment by NAMSGithub** [comment] 2017-10-05 18:55
If they are sessionless I will definitely use one of those two for a workaround.

**Comment by liuxiang625** [comment] 2017-10-11 18:04
I contacted @hamzahik and he confirmed RPC call in 2.x **IS NOT** session-less.

He made it work by updating URL for rpc calls in "proxy.conf.json":

`{
    "/rest/*": {
        "target": "http://127.0.0.1:8081",
        "secure": false,
        "ws": true,
        "headers": {
            "host": "127.0.0.1:8081",
            "origin": "http://127.0.0.1:8081"
        }
    },
    "/rpc-proxy/*": {
        "target": "http://127.0.0.1:8081",
        "secure": false,
        "ws": true,
        "headers": {
            "host": "127.0.0.1:8081",
            "origin": "http://127.0.0.1:8081"
        }
    },
    "/rpc/*": {
        "target": "http://127.0.0.1:8081",
        "secure": false,
        "ws": true,
        "headers": {
            "host": "127.0.0.1:8081",
            "origin": "http://127.0.0.1:8081"
        }
    }
}`

After the change in proxy,  the CORS is no longer needed and can be disabled. 
In addition, the base URL of WAF.core should be ${window.location.origin} instead of "127.0.0.1:8081"

Let me know if it works for you.

**Comment by hamzahik** [comment] 2018-01-16 09:09
@NAMSGithub I'll close this issue. Feel free to reopen it if needed.

**Closed by hamzahik** 2018-01-16 09:09 UTC
