### ISSUE TITLE
Error: Studio locks up when model has an error

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#86] opened 2016-07-14 09:13 UTC
I have been having this issue on and off for a while but lately it has been happening almost all the time.

Here's the scenario

- I go to open a solution.
- there is an error in the model (usually something to do with a related entity)
- a message comes up on screen telling me what the error is.
- I click OK
- Nothing happens – the message stays there and I can’t do anything in Wakanda
- I have to force quit
- If I open the solution again, the same thing happens.
- The only way to fix it is to try to work out what is happening and edit the offending file with a text editor.

Here's a screencast of the issue: https://youtu.be/54ll5m2ZXzI

**Comment by hamzahik** [comment] 2016-07-14 16:14
@chriscurnow this is a known issue and it is normally fixed in the 1.1.0 pre-release.
Can you please confirm that the issue is not reproducible on the 1.1.0 (available on http://wakanda.org if you are using the community version)

**Comment by chriscurnow** [comment] 2016-07-14 22:47
Thanks.

I am using the Enterprise edition – where can I get that?

**Comment by chriscurnow** [comment] 2016-07-17 04:45
@hamzahik I can now confirm this is fixed in the 1.1.0 pre-release. Is there a fix for the Enterprise edition?

**Comment by hamzahik** [comment] 2016-09-22 08:03
1.1.0 released with the fix

**Closed by hamzahik** 2016-09-22 08:03 UTC
Labels: bug, Studio
