### ISSUE TITLE
Object attributes are well created but not updated by save()

### ISSUE THREAD

**Issue by yboukhata** [Wakanda/wakanda-issues#6] opened 2015-07-10 09:04 UTC
<a href="https://github.com/rernens"><img src="https://avatars.githubusercontent.com/u/10088036?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rernens](https://github.com/rernens)**
_Monday Jan 26, 2015 at 17:02 GMT_
_Originally opened as https://github.com/Wakanda/angular-wakanda/issues/6_

----

When updating an entity that contains an object attribute, the changes in the object attributes are not saved without any error being thrown.

Looking at what is being sent by the post request, I discovered that the changes in the object attributes are not reflected in what is being posted.

I will try to workaround the pb but this is a no-go for us.

**Comment by yboukhata** [comment] 2015-07-10 09:04
<a href="https://github.com/rernens"><img src="https://avatars.githubusercontent.com/u/10088036?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rernens](https://github.com/rernens)**
_Tuesday Jan 27, 2015 at 11:08 GMT_

----

there is a workaround.

prior to saving the entity with a modified object atrtibute, backup the object data in a local value
reset the object attribute to {}, save the entity with a promise.
When the promise is successfully fullfillled, assign the value of the local object to the object attribute in the entity and save it again.

Weird but it works and allows us to continue moving forward

**Comment by yboukhata** [comment] 2015-07-10 09:04
<a href="https://github.com/AMorgaut"><img src="https://avatars.githubusercontent.com/u/49318?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AMorgaut](https://github.com/AMorgaut)**
_Tuesday Jan 27, 2015 at 11:32 GMT_

----

Object attributes (vs Entity attributes) are new in Wakanda 10 which is not yet in production, so no specific handling were yet integrated in angular-wakanda and more tests are done at the REST API level.

Still, be sure their support is in the angular-wakanda roadmap for as soon as possible

**Comment by yboukhata** [comment] 2015-07-10 09:04
<a href="https://github.com/JeanL4D"><img src="https://avatars.githubusercontent.com/u/3265930?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JeanL4D](https://github.com/JeanL4D)**
_Tuesday Jan 27, 2015 at 13:32 GMT_

----

If I have understand your problem, a note has been already write in the documention to explain how to modify a oject attribute.
Hope this help.

http://doc.wakanda.org/Datastore/Entity/Working-with-Entities.300-598913.en.html#1070630

Important: To edit the contents of an Object type attribute, you must use an intermediary variable; you cannot assign the value directly to an Object type attribute. For example, if you want to edit the lowerRight property, you must write the following:
var firstEntity  = ds.Shape.first();
var temp = firstEntity.desc ; //variable to store the attribute
temp.lowerRight.x = 6;
temp.lowerRight.y = 6;
firstEntity.desc = temp; //assign the value
// firstEntity.desc.lowerRight.y = 6 is not supported
firstEntity.save();

**Comment by yboukhata** [comment] 2015-07-10 09:04
<a href="https://github.com/rernens"><img src="https://avatars.githubusercontent.com/u/10088036?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rernens](https://github.com/rernens)**
_Saturday Jan 31, 2015 at 12:14 GMT_

----

Thanks for your contribution.
This works in the context of wakanda being used client.side but not when updates are handled through angular wakanda.
The only way to get the object updated is to update the entity twice :
- the first time you save the entity with an empty object
- the second time you save it with an updated object

This way you can update object attributes through angular wakanda $save . Weird because it requires two calls to the server, but it works.

**Comment by yboukhata** [comment] 2015-12-05 12:39
**object attribute** is handled as a simple attribute in the connector.  We will to add additional support to this specific attribute.

**Comment by mrblackus** [comment] 2015-12-10 15:55
As a side note, there is a known issue when trying to set `null` as a value for an object attribute. It's simply ignored. The issue is reported internally and will be fixed soon.

**Comment by hamzahik** [comment] 2015-12-16 14:10
Fixed in https://github.com/Wakanda/angular-wakanda/releases/tag/v1.0.2
Will be included in the next Wakanda release 1.0.1

**Closed by hamzahik** 2015-12-16 14:10 UTC
Labels: Angular-Wakanda, bug
